# for each folder in anda/
# generate a new workflow for each folder in anda/
name: Automatically build packages
on:
  push:
    paths:
      - anda/**
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  manifest:
    runs-on: ubuntu-latest

    outputs:
      build_matrix: ${{ steps.generate_build_matrix.outputs.build_matrix }}
    container:
      image: ghcr.io/terrapkg/builder:main
      options: --cap-add=SYS_ADMIN --privileged
    # check out the repo
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - run: git pull
      #- run: git checkout HEAD^

      # - name: Generate Build matrix
      #   id: generate_build_matrix
      #   # generate build matrix by checking out changes in anda/
      #   run: |
      #     # get the list of changed folders in the current commit, including subfolders
      #     changed_folders=$(git diff --name-only HEAD^ | grep -oP 'anda\/(.+)(\/|\$)' | sort -u )
      #     echo "Changed folders: $changed_folders"
      #     # if changed_folders is empty then set is empty to true
      #     if [ -z "$changed_folders" ]; then
      #       echo "::set-output name=is_empty::true"
      #     else
      #       echo "::set-output name=is_empty::false"
      #     fi
      #     # turn it into a json array
      #     build_matrix=$(echo "$changed_folders" | jq -R . | jq -s . | jq -c .)

      #     echo "::set-output name=build_matrix::$build_matrix"
      #     #echo "::set-output name=build_matrix::$build_matrix"

      - name: Generate build matrix
        id: generate_build_matrix
        run: |
          anda ci >> $GITHUB_OUTPUT
  build:
    needs: manifest
    strategy:
      matrix:
        pkg: ${{ fromJson(needs.manifest.outputs.build_matrix) }}
        version: ["37"]
      fail-fast: false
    #if: ${{ matrix.changed_folders != '' }}
    runs-on: ${{ matrix.pkg.arch == 'aarch64' && 'ARM64' || 'ubuntu-latest' }}
    container:
      image: ghcr.io/terrapkg/builder:main
      options: --cap-add=SYS_ADMIN --privileged
    steps:
      - uses: terrapkg/anda-build@main
        with:
          name: "${{ matrix.pkg.pkg }}"
          mockConfig: anda-${{ matrix.version }}-${{ matrix.pkg.arch }}
          extraArgs: -D "sccache_bucket ${{secrets.SCCACHE_BUCKET}}" -D "sccache_endpoint ${{secrets.SCCACHE_ENDPOINT}}" -D "sccache_secret ${{secrets.SCCACHE_SECRET}}" -D "sccache_accesskey ${{secrets.SCCACHE_ACCESSKEY}}"
          andaRepo: https://github.com/terrapkg/subatomic-repos/raw/main/terra${{ matrix.version }}.repo

      - name: Upload packages to subatomic
        run: |
          subatomic-cli upload --prune \
            --server https://subatomic.fyralabs.com \
            --token ${{ secrets.SUBATOMIC_TOKEN }} \
            terra${{ matrix.version }} anda-build/rpm/rpms/*
