name: Build Packages
on:
  workflow_dispatch:
    inputs:
      packages:
        description: "Packages to Build"
        required: true

jobs:
  parse:
    outputs:
      pkgs: ${{ steps.parsing.outputs.pkgs }}
    runs-on: "ubuntu-latest"
    steps:
      - name: Parse Input
        id: parsing
        run: echo "${{ inputs.packages }}" | sed 's/ /\n/g' | sed 's/$/\//g' | jq -R . | jq -s . | jq -c . | sed 's/^/pkgs=/' >> $GITHUB_OUTPUT
  build:
    needs: parse
    strategy:
      matrix:
        pkg: ${{ fromJson(needs.parse.outputs.pkgs) }}
        version: ["37"]
        arch: ["x86_64", "aarch64"]
      fail-fast: false
    runs-on: ${{ matrix.arch == 'aarch64' && 'ARM64' || 'ubuntu-latest' }}
    container:
      image: ghcr.io/terrapkg/builder:main
      options: --cap-add=SYS_ADMIN --privileged
    steps:
      - uses: terrapkg/anda-build@main
        with:
          name: "${{ matrix.pkg }}pkg"
          mockConfig: anda-37-${{ matrix.arch }}
          extraArgs: -D "sccache_bucket ${{secrets.SCCACHE_BUCKET}}" -D "sccache_endpoint ${{secrets.SCCACHE_ENDPOINT}}" -D "sccache_secret ${{secrets.SCCACHE_SECRET}}" -D "sccache_accesskey ${{secrets.SCCACHE_ACCESSKEY}}"
          andaRepo: https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo

      - name: Upload packages to subatomic
        run: |
          subatomic-cli upload --prune \
            --server https://subatomic.fyralabs.com \
            --token ${{ secrets.SUBATOMIC_TOKEN }} \
            terra${{ matrix.version }} anda-build/rpm/rpms/*

      - name: Notify Madoguchi (Success)
        if: success()
        run: ./.github/workflows/mg.sh true ${{matrix.pkg.pkg}} ${{matrix.version}} ${{matrix.pkg.arch}} ${{github.run_id}} ${{secrets.MADOGUCHI_JWT}}
      - name: Notify Madoguchi (Failure)
        if: cancelled() || failure()
        run: ./.github/workflows/mg.sh false ${{matrix.pkg.pkg}} ${{matrix.version}} ${{matrix.pkg.arch}} ${{github.run_id}} ${{secrets.MADOGUCHI_JWT}}
