name: Push comps updates

on:
  push:
    branches:
      - main
    paths:
      - comps.xml
  workflow_dispatch:

jobs:
  update-comps:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/terrapkg/builder:main
    steps:
      - uses: actions/checkout@v3
      - name: Push to subatomic
        run: |
          subatomic-cli upload-comps \
            --server https://subatomic.fyralabs.com \
            --token ${{ secrets.SUBATOMIC_TOKEN }} \
            terra37 comps.xml
