name: Push comps updates

on:
  push:
    branches:
      - main
    paths:
      - comps.xml
  workflow_dispatch:

jobs:
  update-comps:
    runs-on: ubuntu-latest
    container:
      image: fedora:37
    steps:
      - uses: actions/checkout@v3
      - name: Install repositories
        run: |
          sudo dnf install -y dnf-plugins-core
          sudo dnf config-manager --add-repo https://github.com/andaman-common-pkgs/subatomic-repos/raw/main/terra37.repo
      - name: Install dependencies
        run: |
          sudo dnf install -y subatomic-cli
      - name: Push to subatomic
        run: |
          subatomic-cli upload-comps \
            --server https://subatomic.fyralabs.com \
            --token ${{ secrets.SUBATOMIC_TOKEN }} \
            terra37 comps.xml
