name: Automatically check for updates
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/terrapkg/builder:main
      options: --cap-add=SYS_ADMIN --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.SSH_AUTHENTICATION_KEY }}

      - name: Install SSH signing key
        run: |
          mkdir -p ${{ runner.temp }}
          echo "${{ secrets.SSH_SIGNING_KEY }}" > ${{ runner.temp }}/signing_key
          chmod 0700 ${{ runner.temp }}/signing_key

      - name: Run Update
        run: anda update -vv
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUST_BACKTRACE: full

      - name: Save
        run: |
          git config --global --add safe.directory "*"
          if [[ `git status --porcelain` ]]; then
            git config user.name "Raboneko"
            git config user.email "raboneko@fyralabs.com"
            git config gpg.format "ssh"
            git config user.signingkey "${{ runner.temp }}/signing_key"
            msg="bump: $(git status | grep modified | sed -r 's@.+/([^/]+)/[^/]+\n?@\1 @g' | tr -d '\n')"
            git commit -S -a -m "$msg"
            git format-patch HEAD^
            git checkout f38
            for file in *.patch; do
              git apply $file || true
            done
            rm *.patch
            git commit -S -a -m "$msg"
            git push -u origin --all
          fi
