name: Push comps updates

on:
  push:
    branches:
      - f39
      - f38
      - f37
    paths:
      - comps.xml
  workflow_dispatch:

jobs:
  update-comps:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/terrapkg/builder:main
    steps:
      - uses: actions/checkout@v3
      - id: get-branch
        uses: grandmasterdev/github-action-get-branch@latest
      - name: Push to subatomic
        run: |
          branch=${{steps.get-branch.outputs.branch-name}}
          ver=${branch/f/}
          subatomic-cli upload-comps \
            --server https://subatomic.fyralabs.com \
            --token ${{ secrets.SUBATOMIC_TOKEN }} \
            "terra${ver}" comps.xml
