# for each folder in ultramarine/
# if there is chkupdate.py
# run it every 2 hours
name: Automatically check for updates
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    container:
      image: registry.fedoraproject.org/fedora:37
      options: --cap-add=SYS_ADMIN --privileged
    steps:
      - name: Install packages
        run: dnf install -y rpmdevtools git python

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          ssh-key: ${{ secrets.SSH_AUTHENTICATION_KEY }}
    
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_SIGNING_KEY }}
          known_hosts: unnecessary

      - name: Run Update
        run: bash ./update.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save
        run: |
          git config --global --add safe.directory "*"
          if [[ `git status --porcelain` ]]; then
            git config user.name "Raboneko"
            git config user.email "raboneko@fyralabs.com"
            git config gpg.format "ssh"
            git config gpg.signingKey "${{ secrets.SSH_PUBLIC_SIGNING_KEY }}""
            git commit -S -a -m "Automatic Update: $(git status | grep modified | sed -r 's@.+/([^/]+)/[^/]+\n?@\1 @g' | tr -d '\n')"
            git push -u origin main
          fi
