name: Push comps updates

on:
  push:
    branches:
      - f38
      - f37
    paths:
      - comps.xml
  workflow_dispatch:

jobs:
  update-comps:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/terrapkg/builder:f38
    steps:
      - uses: actions/checkout@v3
      - name: Push to subatomic
        run: |
          branch=${{ github.ref_name }}
          ver=${branch/f/}
          subatomic-cli upload-comps \
            --server https://subatomic.fyralabs.com \
            --token ${{ secrets.SUBATOMIC_TOKEN }} \
            "terra${ver}" comps.xml
